### ISSUE TITLE
Add development instructions to README

### ISSUE THREAD

**Issue by sleddog** [sleddog/cards#2]
This ticket will track the work necessary to add clear development instructions to the readme.

**Comment by bpod** [comment]
I'd like to pick this up, bu I'm not sure exactly what you're looking for. Can you provide more detailed acceptance criteria? What exactly are you trying to provide?

**Comment by sleddog** [comment]
Sure.  Currently the readme has no information as to how to clone, and run the project.

Currently this app is only HTML/JS, so the run instructions are minimal.  Open in a browser.

Also feel free to add any additional documentation/tips you see fit.

**Comment by cheevu-RS** [comment]
What does this project do exactly? I can only see a screen with a green board, images of 4 suites.
![screenshot from 2018-10-02 22-48-20](https://user-images.githubusercontent.com/33937406/46365128-62835100-c695-11e8-974f-5b7f4d1d9de2.png)
